# Generated by Django 3.1.3 on 2020-11-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='title',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
