# Generated by Django 3.1.3 on 2020-12-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_send_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='send',
            name='title',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
