# Generated by Django 3.1.3 on 2020-12-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0003_auto_20201201_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('text', models.TextField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='send',
        ),
    ]
