# Generated by Django 3.1.3 on 2020-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0004_auto_20201201_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(upload_to='file/'),
        ),
    ]
