# Generated by Django 3.1.3 on 2020-12-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0006_auto_20201203_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
