# Generated by Django 3.1.4 on 2020-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0008_auto_20201205_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='username',
            field=models.TextField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='User.username'),
        ),
    ]
