# Generated by Django 3.1.4 on 2020-12-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0009_auto_20201205_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.TextField(default=0, max_length=25),
        ),
    ]
