# Generated by Django 3.1.4 on 2020-12-08 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0010_auto_20201205_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='publishing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Receive'),
        ),
    ]
