# Generated by Django 3.1.4 on 2020-12-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0011_auto_20201208_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='publishing_date',
            field=models.DateTimeField(),
        ),
    ]
