# Generated by Django 3.1.4 on 2020-12-08 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0012_auto_20201208_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='publishing_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 14, 43, 47, 836413, tzinfo=utc)),
        ),
    ]
