# Generated by Django 3.1.4 on 2020-12-08 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0013_auto_20201208_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='publishing_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
