# Generated by Django 3.1.4 on 2020-12-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0014_auto_20201208_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='publishing_date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='time',
            new_name='Time',
        ),
    ]
