# Generated by Django 3.1.4 on 2020-12-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0015_auto_20201208_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Expired',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='Time',
            field=models.TimeField(null=True),
        ),
    ]
