# Generated by Django 3.1.4 on 2020-12-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0016_auto_20201208_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Time',
            field=models.DurationField(null=True),
        ),
    ]
