# Generated by Django 3.1.4 on 2020-12-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0017_auto_20201208_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Time',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
